"""Generate pcb/BOARD_STATE.md -- the component-level and trace-level state
appendix referenced by HANDOFF.md. Machine-generated from the CURRENT board
file so a continuation machine sees exact positions and copper inventory
without opening KiCad.

Sections:
  1. every footprint: ref, value(short), MPN, position, rotation, face
  2. every net's copper inventory: segment count, total length, widths,
     via count, layers used
  3. connectivity: pcbnew ratsnest count + per-net unreached pads (if any)
Run with the KiCad python. Regenerate whenever the board changes.
"""
import sys, os, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pcbnew

BOARD = r"D:\Projects\micromouse-pcb\pcb\micromouse-pcb.kicad_pcb"
OUT = r"D:\Projects\micromouse-pcb\pcb\BOARD_STATE.md"
MM = pcbnew.ToMM

b = pcbnew.LoadBoard(BOARD)
# copper snapshot FIRST (SWIG: GetFootprints degrades track proxies)
tracks = []
vias = []
for t in b.GetTracks():
    net = t.GetNetname()
    if t.GetClass() == "PCB_VIA":
        p = t.GetPosition()
        vias.append((net, round(MM(p.x), 2), round(MM(p.y), 2)))
    else:
        a, c = t.GetStart(), t.GetEnd()
        tracks.append((net, MM(a.x), MM(a.y), MM(c.x), MM(c.y),
                       round(MM(t.GetWidth()), 2), t.GetLayerName()))

fps = []
for fp in b.GetFootprints():
    p = fp.GetPosition()
    mpn = ""
    try:
        mpn = fp.GetFieldByName("MPN").GetText() if fp.HasFieldByName("MPN") else ""
    except Exception:
        pass
    val = fp.GetValue()
    if len(val) > 40:
        val = val[:37] + "..."
    fps.append((fp.GetReference(), val, mpn,
                round(MM(p.x), 2), round(MM(p.y), 2),
                round(fp.GetOrientationDegrees(), 1),
                "B" if fp.IsFlipped() else "F"))

def refkey(r):
    i = 0
    while i < len(r) and not r[i].isdigit():
        i += 1
    return (r[:i], int(r[i:]) if r[i:].isdigit() else 0)

fps.sort(key=lambda t: refkey(t[0]))

# per-net inventory
from collections import defaultdict
inv = defaultdict(lambda: {"n": 0, "len": 0.0, "w": set(), "v": 0, "lay": set()})
for (net, ax, ay, cx, cy, w, lay) in tracks:
    d = inv[net]
    d["n"] += 1
    d["len"] += math.hypot(cx - ax, cy - ay)
    d["w"].add(w)
    d["lay"].add(lay)
for (net, x, y) in vias:
    inv[net]["v"] += 1

# connectivity
pcbnew.ZONE_FILLER(b).Fill(b.Zones())
b.BuildConnectivity()
conn = b.GetConnectivity()
rats = conn.GetUnconnectedCount(True)
unconn = []
for code, ni in b.GetNetsByNetcode().items():
    nm = ni.GetNetname()
    if not nm or nm.startswith("unconnected-"):
        continue
    pads = [p for fp in b.GetFootprints() for p in fp.Pads() if p.GetNetCode() == code]
    if len(pads) < 2:
        continue
    base = pads[0]
    reached = {(round(MM(x.GetPosition().x), 2), round(MM(x.GetPosition().y), 2))
               for x in conn.GetConnectedItems(base) if x.GetClass() == "PAD"}
    bp = base.GetPosition()
    reached.add((round(MM(bp.x), 2), round(MM(bp.y), 2)))
    bad = [(p.GetParentFootprint().GetReference(), p.GetNumber(),
            round(MM(p.GetPosition().x), 2), round(MM(p.GetPosition().y), 2))
           for p in pads[1:]
           if (round(MM(p.GetPosition().x), 2), round(MM(p.GetPosition().y), 2)) not in reached]
    if bad:
        bpp = (base.GetParentFootprint().GetReference(), base.GetNumber(),
               round(MM(bp.x), 2), round(MM(bp.y), 2))
        unconn.append((nm, bpp, bad))

L = ["# BOARD_STATE.md -- machine-generated board snapshot",
     "",
     "Generated by `pcb/tools/gen_board_state.py` from the committed",
     "`micromouse-pcb.kicad_pcb`. Regenerate after any board change.",
     "",
     f"**Copper:** {len(tracks)} track segments, {len(vias)} vias.",
     f"**Connectivity (pcbnew ratsnest, pours filled): {rats} unconnected.**",
     ""]
if unconn:
    L.append("## OPEN CONNECTIONS (must be closed)")
    L.append("")
    L.append("| Net | From (ref.pad @x,y) | Unreached |")
    L.append("|---|---|---|")
    for nm, bpp, bad in sorted(unconn):
        L.append(f"| `{nm}` | {bpp[0]}.{bpp[1]} @({bpp[2]},{bpp[3]}) | "
                 + "; ".join(f"{r}.{n} @({x},{y})" for r, n, x, y in bad) + " |")
    L.append("")
else:
    L.append("## Connectivity: COMPLETE (ratsnest 0)")
    L.append("")

L.append("## Components (ref | value | MPN | x,y | rot | face)")
L.append("")
L.append("| Ref | Value | MPN | x | y | rot | face |")
L.append("|---|---|---|---|---|---|---|")
for (r, v, m, x, y, rot, f) in fps:
    L.append(f"| {r} | {v} | {m} | {x} | {y} | {rot} | {f} |")
L.append("")

L.append("## Net copper inventory (segments | length mm | widths | vias | layers)")
L.append("")
L.append("| Net | segs | len | widths | vias | layers |")
L.append("|---|---|---|---|---|---|")
for net in sorted(inv):
    if not net:
        continue
    d = inv[net]
    L.append(f"| `{net}` | {d['n']} | {d['len']:.1f} | "
             f"{sorted(d['w'])} | {d['v']} | {sorted(d['lay'])} |")
L.append("")

open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
print(f"wrote {OUT}: {len(fps)} components, {len(inv)} nets, ratsnest {rats}")
